/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package TodoApp;

import controller.ProjectController;
import controller.TaskController;
import java.sql.Connection;
import java.util.Date;
import java.util.List;
import model.Project;
import model.Task;
import util.ConnectionFactory;

public class App {
        public static void main(String[] args) {

                // ProjectController projectController = new ProjectController();
                //
                Project project = new Project();
                project.setId(2);
                // project.setName("Projeto teste");
                project.setDescription("description");
                // projectController.save(project);

                ProjectController projectController = new ProjectController();

                project.setName("Novo nome do projeto");
                projectController.update(project);

                List<Project> projects = projectController.getAll();
                System.out.println("Total de projetos" + projects.size());

                // projectController.removeById(1);
                //
                // TaskController taskController = new TaskController();
                //
                // Task task = new Task();
                // task.setIdProject(2);
                // task.setName("Criar as telas da aplicação");
                // task.setDescription("Devem ser criadas telas para os cadastros");
                // task.setNotes("Sem notas");
                // task.setCompleted(false);
                // task.setDeadline(new Date());
                //
                // taskController.save(task);
                //
                // task.setName("Alterar telas da aplicão");
                // taskController.update(task);
                // List<Task> tasks = taskController.getAll(2);
                // System.out.println("Total de tarefas" + tasks.size());

        }

        public Object getGreeting() {
                return null;
        }
}
